// GENERATED FILE. Do not edit by hand. Use scripts/generate-data.mjs to regenerate.

export const currencyCountryData = [
  {
    currencyCode: "AED",
    currencyName: "United Arab Emirates dirham",
    primaryCountryCode: "AE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "AFN",
    currencyName: "Afghan afghani",
    primaryCountryCode: "AF",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ALL",
    currencyName: "Albanian lek",
    primaryCountryCode: "AL",
    otherCountryCodes: [],
  },
  {
    currencyCode: "AMD",
    currencyName: "Armenian dram",
    primaryCountryCode: "AM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean guilder",
    primaryCountryCode: "CW",
    otherCountryCodes: ["SX"],
  },
  {
    currencyCode: "AOA",
    currencyName: "Angolan kwanza",
    primaryCountryCode: "AO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ARS",
    currencyName: "Argentine peso",
    primaryCountryCode: "AR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    primaryCountryCode: "AU",
    otherCountryCodes: ["CC", "CX", "KI", "NF", "NR", "TV"],
  },
  {
    currencyCode: "AWG",
    currencyName: "Aruban florin",
    primaryCountryCode: "AW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "AZN",
    currencyName: "Azerbaijani manat",
    primaryCountryCode: "AZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BAM",
    currencyName: "Bosnia and Herzegovina convertible mark",
    primaryCountryCode: "BA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BBD",
    currencyName: "Barbadian dollar",
    primaryCountryCode: "BB",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BDT",
    currencyName: "Bangladeshi taka",
    primaryCountryCode: "BD",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BGN",
    currencyName: "Bulgarian lev",
    primaryCountryCode: "BG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BHD",
    currencyName: "Bahraini dinar",
    primaryCountryCode: "BH",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BIF",
    currencyName: "Burundian franc",
    primaryCountryCode: "BI",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BMD",
    currencyName: "Bermudian dollar",
    primaryCountryCode: "BM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BND",
    currencyName: "Brunei dollar",
    primaryCountryCode: "BN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BOB",
    currencyName: "Bolivian boliviano",
    primaryCountryCode: "BO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BRL",
    currencyName: "Brazilian real",
    primaryCountryCode: "BR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BSD",
    currencyName: "Bahamian dollar",
    primaryCountryCode: "BS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BTC",
    currencyName: "Bitcoin",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BTN",
    currencyName: "Bhutanese ngultrum",
    primaryCountryCode: "BT",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BWP",
    currencyName: "Botswana pula",
    primaryCountryCode: "BW",
    otherCountryCodes: ["ZW"],
  },
  {
    currencyCode: "BYN",
    currencyName: "Belarusian ruble",
    primaryCountryCode: "BY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "BZD",
    currencyName: "Belize dollar",
    primaryCountryCode: "BZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CAD",
    currencyName: "Canadian dollar",
    primaryCountryCode: "CA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CDF",
    currencyName: "Congolese franc",
    primaryCountryCode: "CD",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CHF",
    currencyName: "Swiss franc",
    primaryCountryCode: "CH",
    otherCountryCodes: ["LI"],
  },
  {
    currencyCode: "CKD",
    currencyName: "Cook Islands dollar",
    primaryCountryCode: "CK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CLF",
    currencyName: "Chilean Unit of Account (UF)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CLP",
    currencyName: "Chilean peso",
    primaryCountryCode: "CL",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CNH",
    currencyName: "Chinese Yuan (Offshore)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CNY",
    currencyName: "Chinese yuan",
    primaryCountryCode: "CN",
    otherCountryCodes: ["ZW"],
  },
  {
    currencyCode: "COP",
    currencyName: "Colombian peso",
    primaryCountryCode: "CO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CRC",
    currencyName: "Costa Rican colón",
    primaryCountryCode: "CR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CUC",
    currencyName: "Cuban convertible peso",
    primaryCountryCode: "CU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CUP",
    currencyName: "Cuban peso",
    primaryCountryCode: "CU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CVE",
    currencyName: "Cape Verdean escudo",
    primaryCountryCode: "CV",
    otherCountryCodes: [],
  },
  {
    currencyCode: "CZK",
    currencyName: "Czech koruna",
    primaryCountryCode: "CZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "DJF",
    currencyName: "Djiboutian franc",
    primaryCountryCode: "DJ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "DKK",
    currencyName: "Danish krone",
    primaryCountryCode: "DK",
    otherCountryCodes: ["FO", "GL"],
  },
  {
    currencyCode: "DOP",
    currencyName: "Dominican peso",
    primaryCountryCode: "DO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "DZD",
    currencyName: "Algerian dinar",
    primaryCountryCode: "DZ",
    otherCountryCodes: ["EH"],
  },
  {
    currencyCode: "EGP",
    currencyName: "Egyptian pound",
    primaryCountryCode: "EG",
    otherCountryCodes: ["PS"],
  },
  {
    currencyCode: "ERN",
    currencyName: "Eritrean nakfa",
    primaryCountryCode: "ER",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ETB",
    currencyName: "Ethiopian birr",
    primaryCountryCode: "ET",
    otherCountryCodes: [],
  },
  {
    currencyCode: "EUR",
    currencyName: "Euro",
    primaryCountryCode: "EU",
    otherCountryCodes: ["AD", "AT", "AX", "BE", "BL", "CY", "DE", "EE", "ES", "FI", "FR", "GF", "GP", "GR", "HR", "IE", "IT", "LT", "LU", "LV", "MC", "ME", "MF", "MQ", "MT", "NL", "PM", "PT", "RE", "SI", "SK", "SM", "TF", "VA", "XK", "YT", "ZW"],
  },
  {
    currencyCode: "FJD",
    currencyName: "Fijian dollar",
    primaryCountryCode: "FJ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "FKP",
    currencyName: "Falkland Islands pound",
    primaryCountryCode: "FK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "FOK",
    currencyName: "Faroese króna",
    primaryCountryCode: "FO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GBP",
    currencyName: "Pound sterling",
    primaryCountryCode: "GB",
    otherCountryCodes: ["GG", "IM", "JE", "SH", "ZW"],
  },
  {
    currencyCode: "GEL",
    currencyName: "lari",
    primaryCountryCode: "GE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GGP",
    currencyName: "Guernsey pound",
    primaryCountryCode: "GG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GHS",
    currencyName: "Ghanaian cedi",
    primaryCountryCode: "GH",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GIP",
    currencyName: "Gibraltar pound",
    primaryCountryCode: "GI",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GMD",
    currencyName: "dalasi",
    primaryCountryCode: "GM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GNF",
    currencyName: "Guinean franc",
    primaryCountryCode: "GN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GTQ",
    currencyName: "Guatemalan quetzal",
    primaryCountryCode: "GT",
    otherCountryCodes: [],
  },
  {
    currencyCode: "GYD",
    currencyName: "Guyanese dollar",
    primaryCountryCode: "GY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "HKD",
    currencyName: "Hong Kong dollar",
    primaryCountryCode: "HK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "HNL",
    currencyName: "Honduran lempira",
    primaryCountryCode: "HN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "HRK",
    currencyName: "Croatian Kuna",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "HTG",
    currencyName: "Haitian gourde",
    primaryCountryCode: "HT",
    otherCountryCodes: [],
  },
  {
    currencyCode: "HUF",
    currencyName: "Hungarian forint",
    primaryCountryCode: "HU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "IDR",
    currencyName: "Indonesian rupiah",
    primaryCountryCode: "ID",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ILS",
    currencyName: "Israeli new shekel",
    primaryCountryCode: "IL",
    otherCountryCodes: ["PS"],
  },
  {
    currencyCode: "IMP",
    currencyName: "Manx pound",
    primaryCountryCode: "IM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "INR",
    currencyName: "Indian rupee",
    primaryCountryCode: "BT",
    otherCountryCodes: ["IN", "ZW"],
  },
  {
    currencyCode: "IQD",
    currencyName: "Iraqi dinar",
    primaryCountryCode: "IQ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "IRR",
    currencyName: "Iranian rial",
    primaryCountryCode: "IR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ISK",
    currencyName: "Icelandic króna",
    primaryCountryCode: "IS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "JEP",
    currencyName: "Jersey pound",
    primaryCountryCode: "JE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "JMD",
    currencyName: "Jamaican dollar",
    primaryCountryCode: "JM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "JOD",
    currencyName: "Jordanian dinar",
    primaryCountryCode: "JO",
    otherCountryCodes: ["PS"],
  },
  {
    currencyCode: "JPY",
    currencyName: "Japanese yen",
    primaryCountryCode: "JP",
    otherCountryCodes: ["ZW"],
  },
  {
    currencyCode: "KES",
    currencyName: "Kenyan shilling",
    primaryCountryCode: "KE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KGS",
    currencyName: "Kyrgyzstani som",
    primaryCountryCode: "KG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KHR",
    currencyName: "Cambodian riel",
    primaryCountryCode: "KH",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KID",
    currencyName: "Kiribati dollar",
    primaryCountryCode: "KI",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KMF",
    currencyName: "Comorian franc",
    primaryCountryCode: "KM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KPW",
    currencyName: "North Korean won",
    primaryCountryCode: "KP",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KRW",
    currencyName: "South Korean won",
    primaryCountryCode: "KR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KWD",
    currencyName: "Kuwaiti dinar",
    primaryCountryCode: "KW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KYD",
    currencyName: "Cayman Islands dollar",
    primaryCountryCode: "KY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "KZT",
    currencyName: "Kazakhstani tenge",
    primaryCountryCode: "KZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LAK",
    currencyName: "Lao kip",
    primaryCountryCode: "LA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LBP",
    currencyName: "Lebanese pound",
    primaryCountryCode: "LB",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LKR",
    currencyName: "Sri Lankan rupee",
    primaryCountryCode: "LK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LRD",
    currencyName: "Liberian dollar",
    primaryCountryCode: "LR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LSL",
    currencyName: "Lesotho loti",
    primaryCountryCode: "LS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "LYD",
    currencyName: "Libyan dinar",
    primaryCountryCode: "LY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MAD",
    currencyName: "Moroccan dirham",
    primaryCountryCode: "EH",
    otherCountryCodes: ["MA"],
  },
  {
    currencyCode: "MDL",
    currencyName: "Moldovan leu",
    primaryCountryCode: "MD",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MGA",
    currencyName: "Malagasy ariary",
    primaryCountryCode: "MG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MKD",
    currencyName: "denar",
    primaryCountryCode: "MK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MMK",
    currencyName: "Burmese kyat",
    primaryCountryCode: "MM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MNT",
    currencyName: "Mongolian tögrög",
    primaryCountryCode: "MN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MOP",
    currencyName: "Macanese pataca",
    primaryCountryCode: "MO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MRU",
    currencyName: "Mauritanian ouguiya",
    primaryCountryCode: "EH",
    otherCountryCodes: ["MR"],
  },
  {
    currencyCode: "MUR",
    currencyName: "Mauritian rupee",
    primaryCountryCode: "MU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MVR",
    currencyName: "Maldivian rufiyaa",
    primaryCountryCode: "MV",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MWK",
    currencyName: "Malawian kwacha",
    primaryCountryCode: "MW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MXN",
    currencyName: "Mexican peso",
    primaryCountryCode: "MX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MYR",
    currencyName: "Malaysian ringgit",
    primaryCountryCode: "MY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "MZN",
    currencyName: "Mozambican metical",
    primaryCountryCode: "MZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "NAD",
    currencyName: "Namibian dollar",
    primaryCountryCode: "NA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "NGN",
    currencyName: "Nigerian naira",
    primaryCountryCode: "NG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "NIO",
    currencyName: "Nicaraguan córdoba",
    primaryCountryCode: "NI",
    otherCountryCodes: [],
  },
  {
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    primaryCountryCode: "NO",
    otherCountryCodes: ["SJ"],
  },
  {
    currencyCode: "NPR",
    currencyName: "Nepalese rupee",
    primaryCountryCode: "NP",
    otherCountryCodes: [],
  },
  {
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    primaryCountryCode: "CK",
    otherCountryCodes: ["NU", "NZ", "PN", "TK"],
  },
  {
    currencyCode: "OMR",
    currencyName: "Omani rial",
    primaryCountryCode: "OM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PAB",
    currencyName: "Panamanian balboa",
    primaryCountryCode: "PA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PEN",
    currencyName: "Peruvian sol",
    primaryCountryCode: "PE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PGK",
    currencyName: "Papua New Guinean kina",
    primaryCountryCode: "PG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PHP",
    currencyName: "Philippine peso",
    primaryCountryCode: "PH",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PKR",
    currencyName: "Pakistani rupee",
    primaryCountryCode: "PK",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PLN",
    currencyName: "Polish złoty",
    primaryCountryCode: "PL",
    otherCountryCodes: [],
  },
  {
    currencyCode: "PYG",
    currencyName: "Paraguayan guaraní",
    primaryCountryCode: "PY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "QAR",
    currencyName: "Qatari riyal",
    primaryCountryCode: "QA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "RON",
    currencyName: "Romanian leu",
    primaryCountryCode: "RO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "RSD",
    currencyName: "Serbian dinar",
    primaryCountryCode: "RS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "RUB",
    currencyName: "Russian ruble",
    primaryCountryCode: "RU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "RWF",
    currencyName: "Rwandan franc",
    primaryCountryCode: "RW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SAR",
    currencyName: "Saudi riyal",
    primaryCountryCode: "SA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SBD",
    currencyName: "Solomon Islands dollar",
    primaryCountryCode: "SB",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SCR",
    currencyName: "Seychellois rupee",
    primaryCountryCode: "SC",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SDG",
    currencyName: "Sudanese pound",
    primaryCountryCode: "SD",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SEK",
    currencyName: "Swedish krona",
    primaryCountryCode: "SE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SGD",
    currencyName: "Singapore dollar",
    primaryCountryCode: "SG",
    otherCountryCodes: ["BN"],
  },
  {
    currencyCode: "SHP",
    currencyName: "Saint Helena pound",
    primaryCountryCode: "GS",
    otherCountryCodes: ["SH"],
  },
  {
    currencyCode: "SLE",
    currencyName: "Sierra Leonean Leone",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SLL",
    currencyName: "Sierra Leonean leone",
    primaryCountryCode: "SL",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SOS",
    currencyName: "Somali shilling",
    primaryCountryCode: "SO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SRD",
    currencyName: "Surinamese dollar",
    primaryCountryCode: "SR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SSP",
    currencyName: "South Sudanese pound",
    primaryCountryCode: "SS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "STD",
    currencyName: "São Tomé and Príncipe Dobra (pre-2018)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "STN",
    currencyName: "São Tomé and Príncipe dobra",
    primaryCountryCode: "ST",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SVC",
    currencyName: "Salvadoran Colón",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SYP",
    currencyName: "Syrian pound",
    primaryCountryCode: "SY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "SZL",
    currencyName: "Swazi lilangeni",
    primaryCountryCode: "SZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "THB",
    currencyName: "Thai baht",
    primaryCountryCode: "TH",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TJS",
    currencyName: "Tajikistani somoni",
    primaryCountryCode: "TJ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TMT",
    currencyName: "Turkmenistan manat",
    primaryCountryCode: "TM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TND",
    currencyName: "Tunisian dinar",
    primaryCountryCode: "TN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TOP",
    currencyName: "Tongan paʻanga",
    primaryCountryCode: "TO",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TRY",
    currencyName: "Turkish lira",
    primaryCountryCode: "TR",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago dollar",
    primaryCountryCode: "TT",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TVD",
    currencyName: "Tuvaluan dollar",
    primaryCountryCode: "TV",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TWD",
    currencyName: "New Taiwan dollar",
    primaryCountryCode: "TW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "TZS",
    currencyName: "Tanzanian shilling",
    primaryCountryCode: "TZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "UAH",
    currencyName: "Ukrainian hryvnia",
    primaryCountryCode: "UA",
    otherCountryCodes: [],
  },
  {
    currencyCode: "UGX",
    currencyName: "Ugandan shilling",
    primaryCountryCode: "UG",
    otherCountryCodes: [],
  },
  {
    currencyCode: "USD",
    currencyName: "United States dollar",
    primaryCountryCode: "US",
    otherCountryCodes: ["AS", "BQ", "BS", "EC", "GU", "IO", "KH", "MH", "MP", "PA", "PR", "PW", "SV", "TC", "TL", "UM", "VG", "VI", "ZW"],
  },
  {
    currencyCode: "UYU",
    currencyName: "Uruguayan peso",
    primaryCountryCode: "UY",
    otherCountryCodes: [],
  },
  {
    currencyCode: "UZS",
    currencyName: "Uzbekistani soʻm",
    primaryCountryCode: "UZ",
    otherCountryCodes: [],
  },
  {
    currencyCode: "VEF",
    currencyName: "Venezuelan Bolívar Fuerte (Old)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "VES",
    currencyName: "Venezuelan bolívar soberano",
    primaryCountryCode: "VE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "VND",
    currencyName: "Vietnamese đồng",
    primaryCountryCode: "VN",
    otherCountryCodes: [],
  },
  {
    currencyCode: "VUV",
    currencyName: "Vanuatu vatu",
    primaryCountryCode: "VU",
    otherCountryCodes: [],
  },
  {
    currencyCode: "WST",
    currencyName: "Samoan tālā",
    primaryCountryCode: "WS",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    primaryCountryCode: "CM",
    otherCountryCodes: ["CF", "CG", "GA", "GQ", "TD"],
  },
  {
    currencyCode: "XAG",
    currencyName: "Silver Ounce",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XAU",
    currencyName: "Gold Ounce",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XBA",
    currencyName: "Bond Markets Unit European Composite Unit (EURCO)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XBB",
    currencyName: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XBC",
    currencyName: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XBD",
    currencyName: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XCD",
    currencyName: "Eastern Caribbean dollar",
    primaryCountryCode: "AG",
    otherCountryCodes: ["AI", "DM", "GD", "KN", "LC", "MS", "VC"],
  },
  {
    currencyCode: "XCG",
    currencyName: "Caribbean Guilder",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XDR",
    currencyName: "Special Drawing Rights",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    primaryCountryCode: "SN",
    otherCountryCodes: ["BF", "BJ", "CI", "GW", "ML", "NE", "TG"],
  },
  {
    currencyCode: "XPD",
    currencyName: "Palladium Ounce",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XPF",
    currencyName: "CFP franc",
    primaryCountryCode: "NC",
    otherCountryCodes: ["PF", "WF"],
  },
  {
    currencyCode: "XPT",
    currencyName: "Platinum Ounce",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XSU",
    currencyName: "Sucre",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XTS",
    currencyName: "Codes specifically reserved for testing purposes",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XUA",
    currencyName: "ADB Unit of Account",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "XXX",
    currencyName: "No currency",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "YER",
    currencyName: "Yemeni rial",
    primaryCountryCode: "YE",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ZAR",
    currencyName: "South African rand",
    primaryCountryCode: "LS",
    otherCountryCodes: ["NA", "SZ", "ZA", "ZW"],
  },
  {
    currencyCode: "ZMW",
    currencyName: "Zambian kwacha",
    primaryCountryCode: "ZM",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ZWB",
    currencyName: "Zimbabwean bonds",
    primaryCountryCode: "ZW",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ZWG",
    currencyName: "Zimbabwean ZiG",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
  {
    currencyCode: "ZWL",
    currencyName: "Zimbabwean Dollar",
    primaryCountryCode: "XX",
    otherCountryCodes: [],
  },
];

export const currencyNameAliases = {
  USD: ["US Dollar", "Dollar", "American Dollar"],
  EUR: ["Eurozone Euro"],
  GBP: ["British Pound", "Sterling"],
  AUD: ["Aussie Dollar"],
  NZD: ["Kiwi Dollar"],
  CHF: ["Swiss Franc"],
  CNY: ["Renminbi", "Yuan Renminbi"],
  JPY: ["Yen"],
  HKD: ["Hong Kong Dollar"],
  SGD: ["Singapore Dollar"],
  INR: ["Indian Rupee"],
  AED: ["Dirham", "UAE Dirham"],
  SAR: ["Saudi Riyal"],
  KWD: ["Kuwaiti Dinar"],
  QAR: ["Qatari Riyal"],
  BHD: ["Bahraini Dinar"],
  OMR: ["Omani Rial"],
  TRY: ["Turkish Lira"],
  EGP: ["Egyptian Pound"],
  RUB: ["Russian Ruble", "Ruble"],
  SEK: ["Swedish Krona"],
  NOK: ["Norwegian Krone"],
  DKK: ["Danish Krone"],
  XAF: ["CFA Franc BEAC", "Central African CFA"],
  XOF: ["CFA Franc BCEAO", "West African CFA"],
  ZAR: ["South African Rand", "Rand"],
};
